# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget VexCL::Common VexCL::OpenCL VexCL::Compute VexCL::JIT)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target VexCL::Common
add_library(VexCL::Common INTERFACE IMPORTED)

set_target_properties(VexCL::Common PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<CXX_COMPILER_ID:MSVC>:NOMINMAX>;\$<\$<CXX_COMPILER_ID:MSVC>:_VARIADIC_MAX=10>"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:GNU>:-std=c++0x>;\$<\$<CXX_COMPILER_ID:GNU>:-Wall>;\$<\$<CXX_COMPILER_ID:GNU>:-Wno-missing-braces>;\$<\$<CXX_COMPILER_ID:GNU>:-Wno-deprecated-declarations>;\$<\$<CXX_COMPILER_ID:GNU>:-Wno-ignored-attributes>;\$<\$<CXX_COMPILER_ID:GNU>:-Wno-unused-local-typedefs>;\$<\$<CXX_COMPILER_ID:Clang>:-std=c++0x>;\$<\$<CXX_COMPILER_ID:Clang>:-Wall>;\$<\$<CXX_COMPILER_ID:Clang>:-Wno-missing-braces>;\$<\$<CXX_COMPILER_ID:Clang>:-Wno-deprecated-declarations>;\$<\$<CXX_COMPILER_ID:Clang>:-Wno-ignored-attributes>;\$<\$<CXX_COMPILER_ID:MSVC>:/bigobj>;\$<\$<CXX_COMPILER_ID:MSVC>:/wd4003>;\$<\$<CXX_COMPILER_ID:MSVC>:/wd4996>"
  INTERFACE_INCLUDE_DIRECTORIES "/usr/local/include;/Users/filippovicentini/Desktop/vexcl-1.4.1"
  INTERFACE_LINK_LIBRARIES "/usr/local/lib/libboost_filesystem-mt.dylib;/usr/local/lib/libboost_system-mt.dylib;/usr/local/lib/libboost_thread-mt.dylib"
)

# Create imported target VexCL::OpenCL
add_library(VexCL::OpenCL INTERFACE IMPORTED)

set_target_properties(VexCL::OpenCL PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "VEXCL_BACKEND_OPENCL"
  INTERFACE_INCLUDE_DIRECTORIES "/System/Library/Frameworks/OpenCL.framework"
  INTERFACE_LINK_LIBRARIES "VexCL::Common;/System/Library/Frameworks/OpenCL.framework"
)

# Create imported target VexCL::Compute
add_library(VexCL::Compute INTERFACE IMPORTED)

set_target_properties(VexCL::Compute PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "VEXCL_BACKEND_COMPUTE"
  INTERFACE_INCLUDE_DIRECTORIES "/System/Library/Frameworks/OpenCL.framework"
  INTERFACE_LINK_LIBRARIES "VexCL::Common;/System/Library/Frameworks/OpenCL.framework"
)

# Create imported target VexCL::JIT
add_library(VexCL::JIT INTERFACE IMPORTED)

set_target_properties(VexCL::JIT PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "VEXCL_BACKEND_JIT"
  INTERFACE_COMPILE_OPTIONS "NOTFOUND"
  INTERFACE_LINK_LIBRARIES "VexCL::Common;\$<\$<CXX_COMPILER_ID:GNU>:NOTFOUND;dl>;\$<\$<CXX_COMPILER_ID:Clang>:NOTFOUND;dl>;\$<\$<CXX_COMPILER_ID:Intel>:NOTFOUND;dl>"
)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
