//
// Created by Filippo Vicentini on 22/02/2018.
//

#ifndef SIMULATOR_MPIPINCOTAGS_HPP
#define SIMULATOR_MPIPINCOTAGS_HPP

#define MASTER_RANK 0

#define SOLVER_STRING_MESSAGE_TAG 1
#define TASKDATA_VECTOR_MESSAGE_TAG 2
#define TASKRESULTS_VECTOR_MESSAGE_TAG 3

#define TERMINATE_WHEN_DONE_MESSAGE_TAG 15
#define NODE_TERMINATED_MESSAGE_TAG 16
#define NODE_PROGRESS_MESSAGE_TAG 17

#endif //SIMULATOR_MPIPINCOTAGS_HPP
